### ISSUE TITLE
upgrade to amqplib 0.6.0 as 0.5.6 break with node LTS (14.15.0)

### ISSUE THREAD

**Issue by PierreKauffmann** [log4js-node/rabbitmq#19]
Please update the dependencies on amqplib to support latest Node LTS

npm WARN notsup Unsupported engine for amqplib@0.5.6: wanted: {"node":">=0.8 <=12"} (current: {"node":"14.15.0","npm":"6.14.8"})

**Comment by nomiddlename** [comment]
Fixed by #27
